import type { TaskAutomationLevel, ExecutionEnvironment } from '../types';

export interface CategoryCapabilityContract {
  category: string;
  displayName: string;
  aliases: string[];
  automationLevel: TaskAutomationLevel;
  primaryProviderId: string;
  fallbackProviderId: string;
  supportsSearch: boolean;
  supportsAvailability: boolean;
  supportsPricingQuote: boolean;
  supportsDirectExecution: boolean;
  supportsModification: boolean;
  supportsCancellation: boolean;
  supportsConfirmationValidation: boolean;
  completionCriterion:
    | 'GENUINE_PNR'
    | 'HOTEL_CONFIRMATION'
    | 'RESERVATION_CONFIRMATION'
    | 'DELIVERY_ORDER_ID'
    | 'RIDE_BOOKING_ID'
    | 'TICKET_REFERENCE'
    | 'COMMERCE_ORDER_ID'
    | 'APPOINTMENT_CONFIRMATION'
    | 'EVENT_PASS_REFERENCE'
    | 'COMPOSITE_ALL_VERIFIED'
    | 'VALIDATED_DELIVERABLE'
    | 'OPERATOR_VERIFIED_CONFIRMATION';
  requiredInputs: string[];
  optionalInputs: string[];
  hardConstraints: string[];
  recommendationStrategy: string;
  exactly5OptionsStrategy: string;
  executionMethod: 'API_DIRECT' | 'ASSISTED_CONCIERGE' | 'HUMAN_OPERATOR' | 'DELIVERABLE_COMPLETION' | 'COMPOSITE_ORCHESTRATION';
  requiresPaymentAuthorization: boolean;
  requiresBookingReference: boolean;
  confirmationRequirement: string;
  modificationStrategy: 'AUTOMATED_API' | 'ASSISTED_OPERATOR' | 'POLICY_BLOCKED';
  cancellationStrategy: 'AUTOMATED_API' | 'ASSISTED_OPERATOR' | 'POLICY_BLOCKED';
  escalationTriggers: string[];
}

export const CATEGORY_AUTOMATION_CONTRACTS: Record<string, CategoryCapabilityContract> = {
  flights: {
    category: 'flights',
    displayName: 'Aviation & Flight Bookings',
    aliases: ['flights', 'flight', 'travel', 'airline', 'air_travel'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'amadeus_flights',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'GENUINE_PNR',
    requiredInputs: ['destination', 'origin', 'departureDate', 'passengers'],
    optionalInputs: ['cabinClass', 'departureTimePreference', 'returnDate', 'preferredAirlines', 'seatPreference'],
    hardConstraints: ['origin', 'destination', 'cabinClass', 'passengerCount', 'departureDate'],
    recommendationStrategy: 'Airline GDS direct schedules sorted by nonstop preference, timing precision, and member tier',
    exactly5OptionsStrategy: 'Ranked top 5 non-overlapping flight itineraries matching corridor and cabin class',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Valid 6-character airline PNR verified against carrier reservation system',
    modificationStrategy: 'AUTOMATED_API',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'GDS ticketing rate mismatch > 5%',
      'Fare class sold out during booking checkout',
      'Name mismatch with passport record',
      'Carrier API service outage',
    ],
  },
  hotels: {
    category: 'hotels',
    displayName: 'Luxury Hotels & Accommodations',
    aliases: ['hotels', 'hotel', 'hotels_accommodation', 'accommodation', 'stay', 'resort', 'villa'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_hotels',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'HOTEL_CONFIRMATION',
    requiredInputs: ['destination', 'checkInDate', 'nights', 'guests'],
    optionalInputs: ['roomType', 'amenityPreferences', 'bedType', 'maxBudgetPerNight', 'hotelBrand'],
    hardConstraints: ['destination', 'checkInDate', 'nights', 'guestCapacity'],
    recommendationStrategy: '5-star & luxury boutique properties filtered by city matching, luxury score, and private perks',
    exactly5OptionsStrategy: '5 distinct verified luxury properties with instant booking allocation',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Direct hotel reservation confirmation number with room category and stay dates',
    modificationStrategy: 'AUTOMATED_API',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Property room inventory exhausted',
      'Special VIP arrival suite upgrade requested',
      'Direct partner desk telephone confirmation required',
    ],
  },
  dining: {
    category: 'dining',
    displayName: 'Fine Dining & Culinary Reservations',
    aliases: ['dining', 'restaurant', 'fine_dining', 'table_booking', 'culinary'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'swiggy_dineout',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'RESERVATION_CONFIRMATION',
    requiredInputs: ['location', 'partySize', 'dateTime'],
    optionalInputs: ['cuisinePreference', 'seatingArea', 'dietaryRestrictions', 'specialOccasion'],
    hardConstraints: ['location', 'partySize', 'dateTime'],
    recommendationStrategy: 'Michelin / award-winning / curated chef tables matched to customer palate and occasion',
    exactly5OptionsStrategy: '5 premier culinary establishments with guaranteed table seating slots',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: false,
    requiresBookingReference: true,
    confirmationRequirement: 'Confirmed table booking ID from restaurant reservation portal or duty manager confirmation',
    modificationStrategy: 'AUTOMATED_API',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Prime dining slot requires telephone maître d’ reservation',
      'Private dining room exclusivity deposit required',
      'Dress code / minimum spend consultation needed',
    ],
  },
  food_delivery: {
    category: 'food_delivery',
    displayName: 'Artisan Food & Gourmet Delivery',
    aliases: ['food_delivery', 'food', 'delivery', 'gourmet', 'catering'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'swiggy_dineout',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: false,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'DELIVERY_ORDER_ID',
    requiredInputs: ['deliveryAddress', 'cuisineOrItems'],
    optionalInputs: ['deliveryTime', 'dietaryRestrictions', 'spiceLevel', 'specialInstructions'],
    hardConstraints: ['deliveryAddress', 'dietaryRestrictions'],
    recommendationStrategy: 'Top-rated gourmet kitchens and artisan menus with fast white-glove packaging',
    exactly5OptionsStrategy: '5 curated restaurant menus or gourmet selections available for delivery',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Live order tracking ID and kitchen fulfillment dispatch code',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Restaurant kitchen closed',
      'Out of delivery radius',
      'Custom catering menu requires special kitchen preparation',
    ],
  },
  transportation: {
    category: 'transportation',
    displayName: 'Luxury Mobility & Chauffeur Services',
    aliases: ['transportation', 'mobility', 'transport', 'transit', 'chauffeur', 'car_rental'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_mobility',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'RIDE_BOOKING_ID',
    requiredInputs: ['pickupLocation', 'dropoffLocation', 'pickupTime'],
    optionalInputs: ['vehicleClass', 'passengerCount', 'luggageCount', 'flightNumberForTracking'],
    hardConstraints: ['pickupLocation', 'dropoffLocation', 'pickupTime'],
    recommendationStrategy: 'Executive sedans, SUVs, and luxury electric fleets with vetted chauffeurs',
    exactly5OptionsStrategy: '5 vehicle class options with transparent all-inclusive hourly/trip rates',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Driver dispatch reservation reference with vehicle make and pickup schedule',
    modificationStrategy: 'AUTOMATED_API',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Airport tarmac VIP vehicle permit requested',
      'Armored vehicle or multi-day convoy required',
      'Severe weather or road closure rerouting',
    ],
  },
  movies_entertainment: {
    category: 'movies_entertainment',
    displayName: 'Cinema, Theatres & Entertainment',
    aliases: ['movies_entertainment', 'movies', 'movie', 'cinema', 'experiences', 'entertainment', 'tickets'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'cinema_pvr_inox',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: false,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'TICKET_REFERENCE',
    requiredInputs: ['titleOrExperience', 'city', 'dateTime'],
    optionalInputs: ['auditoriumFormat', 'seatingPreference', 'numberOfTickets'],
    hardConstraints: ['titleOrExperience', 'city', 'dateTime'],
    recommendationStrategy: 'IMAX Laser, Director’s Cut, and VIP recliner auditoriums with in-seat service',
    exactly5OptionsStrategy: '5 luxury showtimes or venue auditoriums matching the requested timing',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'M-Ticket QR booking reference and confirmed seat numbers',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Entire luxury screening hall private buyout requested',
      'Sold out premiere access required',
    ],
  },
  gifts: {
    category: 'gifts',
    displayName: 'Curated Gifting & Luxury Hampers',
    aliases: ['gifts', 'gift', 'curated_gifting'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_shopping',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: false,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'COMMERCE_ORDER_ID',
    requiredInputs: ['budgetOrOccasion', 'recipientOrTheme'],
    optionalInputs: ['recipientAddress', 'customNote', 'deliveryDate', 'wrappingStyle'],
    hardConstraints: ['budgetRange', 'deliveryTimeline'],
    recommendationStrategy: 'Artisanal, bespoke, and heritage luxury collections within target budget',
    exactly5OptionsStrategy: '5 distinct handcrafted hampers, fine goods, or rare collector items',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Order ID with courier tracking code and gift card message verification',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Custom gold/silver engraving or bespoke personalization needed',
      'Immediate 2-hour international courier dispatch',
    ],
  },
  shopping: {
    category: 'shopping',
    displayName: 'Boutique Shopping & Luxury Retail',
    aliases: ['shopping', 'luxury_retail', 'personal_shopper'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_shopping',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: false,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'COMMERCE_ORDER_ID',
    requiredInputs: ['itemOrBrand', 'sizeOrSpecs'],
    optionalInputs: ['deliveryAddress', 'colorPreference', 'budgetLimit'],
    hardConstraints: ['itemSpecifications'],
    recommendationStrategy: 'Authorized luxury boutiques and direct atelier flagship stock',
    exactly5OptionsStrategy: '5 verified genuine product editions with transparent pricing',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Authorized retail invoice number and dispatch tracking details',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: [
      'Hermès / Rolex / Patek waitlist or rare allocation sourcing',
      'In-person personal shopper fitting at private residence',
    ],
  },
  salon: {
    category: 'salon',
    displayName: 'Haute Coiffure & Salon Appointments',
    aliases: ['salon', 'hair', 'grooming', 'barber'],
    automationLevel: 'ASSISTED',
    primaryProviderId: 'ahmedabad_verified',
    fallbackProviderId: 'mock_dining',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'APPOINTMENT_CONFIRMATION',
    requiredInputs: ['serviceType', 'dateTime', 'preferredStylist'],
    optionalInputs: ['locationPreference', 'gender', 'vipRoomRequired'],
    hardConstraints: ['serviceType', 'dateTime'],
    recommendationStrategy: 'Master stylist salons and private VIP grooming studios',
    exactly5OptionsStrategy: '5 premier salon packages with confirmed specialist time slots',
    executionMethod: 'ASSISTED_CONCIERGE',
    requiresPaymentAuthorization: false,
    requiresBookingReference: true,
    confirmationRequirement: 'Direct salon booking confirmation with named senior stylist and appointment time',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'ASSISTED_OPERATOR',
    escalationTriggers: ['Celebrity stylist private appointment requested', 'In-suite private grooming team dispatch'],
  },
  wellness: {
    category: 'wellness',
    displayName: 'Spa, Ayurveda & Wellness Retreats',
    aliases: ['wellness', 'spa', 'massage', 'ayurveda', 'holistic'],
    automationLevel: 'ASSISTED',
    primaryProviderId: 'ahmedabad_verified',
    fallbackProviderId: 'mock_hotels',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'APPOINTMENT_CONFIRMATION',
    requiredInputs: ['treatmentType', 'dateTime', 'guestsCount'],
    optionalInputs: ['therapistPreference', 'privateCouplesSuite', 'healthNotes'],
    hardConstraints: ['treatmentType', 'dateTime'],
    recommendationStrategy: 'Kaya Kalp, Jiva, and Ananda-accredited holistic spas with private suites',
    exactly5OptionsStrategy: '5 verified spa & therapy curations with dedicated treatment timings',
    executionMethod: 'ASSISTED_CONCIERGE',
    requiresPaymentAuthorization: false,
    requiresBookingReference: true,
    confirmationRequirement: 'Confirmed spa appointment slip with treatment name and scheduled duration',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'ASSISTED_OPERATOR',
    escalationTriggers: ['Medical / Ayurvedic doctor consultation requirement', 'Full-day wellness sanctuary buyout'],
  },
  appointments: {
    category: 'appointments',
    displayName: 'Calendar & Professional Appointments',
    aliases: ['appointments', 'appointment', 'calendar', 'consultation'],
    automationLevel: 'ASSISTED',
    primaryProviderId: 'ahmedabad_verified',
    fallbackProviderId: 'mock_research_planning',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'APPOINTMENT_CONFIRMATION',
    requiredInputs: ['counterpartyOrSpecialist', 'preferredDate', 'topicOrPurpose'],
    optionalInputs: ['meetingType', 'duration', 'preferredTimeSlot'],
    hardConstraints: ['preferredDate', 'specialistTopic'],
    recommendationStrategy: 'Direct executive scheduling with verified partner coordinators',
    exactly5OptionsStrategy: '5 scheduling windows or specialist consultation slots',
    executionMethod: 'ASSISTED_CONCIERGE',
    requiresPaymentAuthorization: false,
    requiresBookingReference: true,
    confirmationRequirement: 'Calendar invite confirmation with meeting location or secure conference bridge link',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'ASSISTED_OPERATOR',
    escalationTriggers: ['High-level diplomatic or C-suite executive coordination'],
  },
  events: {
    category: 'events',
    displayName: 'Gala, Concerts & High-Profile Events',
    aliases: ['events', 'event', 'business', 'gatherings', 'gala', 'summit'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'cinema_pvr_inox',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: false,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'EVENT_PASS_REFERENCE',
    requiredInputs: ['eventNameOrType', 'city', 'date'],
    optionalInputs: ['vipLoungeAccess', 'numberOfPasses', 'budget'],
    hardConstraints: ['eventNameOrType', 'city', 'date'],
    recommendationStrategy: 'VIP access tiers, box passes, and exclusive private member hospitality',
    exactly5OptionsStrategy: '5 ticket/hospitality packages with verified seating privileges',
    executionMethod: 'API_DIRECT',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Event registration barcode / VIP badge pickup reference',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: ['Backstage VIP artist meet & greet pass request', 'Private corporate hospitality suite buyout'],
  },
  weekend_escapes: {
    category: 'weekend_escapes',
    displayName: 'Curated Weekend Escapes & Multi-Service Trips',
    aliases: ['weekend_escapes', 'weekend_escape', 'getaways', 'vacation_package'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_hotels',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'COMPOSITE_ALL_VERIFIED',
    requiredInputs: ['partySize', 'datesOrWeekend'],
    optionalInputs: ['destinationPreference', 'interests', 'budgetLevel', 'transportMode'],
    hardConstraints: ['partySize', 'tripDates'],
    recommendationStrategy: 'Holistic packages combining luxury stay, private transport, and curated dining experiences',
    exactly5OptionsStrategy: '5 comprehensive weekend escape itineraries with all components itemized',
    executionMethod: 'COMPOSITE_ORCHESTRATION',
    requiresPaymentAuthorization: true,
    requiresBookingReference: true,
    confirmationRequirement: 'Verified confirmations for ALL mandatory sub-components (Stay + Chauffeur + Dining)',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'ASSISTED_OPERATOR',
    escalationTriggers: [
      'One mandatory sub-component failed execution',
      'Private charter flight or yacht charter required',
    ],
  },
  travel_planning: {
    category: 'travel_planning',
    displayName: 'Executive Travel Planning & Dossiers',
    aliases: ['travel_planning', 'planning', 'itinerary', 'curation'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_research_planning',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: false,
    supportsPricingQuote: false,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'VALIDATED_DELIVERABLE',
    requiredInputs: ['destination', 'durationOrPacing'],
    optionalInputs: ['interests', 'travelersProfile', 'budgetPreferences'],
    hardConstraints: ['destination'],
    recommendationStrategy: 'Expert cultural, architectural, and insider culinary intelligence dossiers',
    exactly5OptionsStrategy: '5 distinct thematic travel dossiers (e.g. Heritage, Gastronomy, Art & Design)',
    executionMethod: 'DELIVERABLE_COMPLETION',
    requiresPaymentAuthorization: false,
    requiresBookingReference: false,
    confirmationRequirement: 'Validated, structured executive itinerary dossier delivered directly to client',
    modificationStrategy: 'AUTOMATED_API',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: ['Custom multi-country visa & private aircraft routing consultation'],
  },
  research: {
    category: 'research',
    displayName: 'Research, Advisory & Market Intelligence',
    aliases: ['research', 'personal', 'advisory', 'intelligence', 'analysis'],
    automationLevel: 'AUTOMATED',
    primaryProviderId: 'mock_research_planning',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: false,
    supportsPricingQuote: false,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'VALIDATED_DELIVERABLE',
    requiredInputs: ['researchSubjectOrQuery'],
    optionalInputs: ['depthLevel', 'deadline', 'formatPreferences'],
    hardConstraints: ['researchSubjectOrQuery'],
    recommendationStrategy: 'Methodical synthesis, comparative benchmarks, and authoritative verified sources',
    exactly5OptionsStrategy: '5 distinct analytical angles or research deliverables tailored to the inquiry',
    executionMethod: 'DELIVERABLE_COMPLETION',
    requiresPaymentAuthorization: false,
    requiresBookingReference: false,
    confirmationRequirement: 'Complete, structured executive advisory brief delivered to client',
    modificationStrategy: 'AUTOMATED_API',
    cancellationStrategy: 'AUTOMATED_API',
    escalationTriggers: ['Confidential cross-border legal or commercial due diligence requested'],
  },
  other_concierge: {
    category: 'other_concierge',
    displayName: 'Bespoke Private Concierge Requests',
    aliases: ['other_concierge', 'other', 'concierge', 'custom_request'],
    automationLevel: 'HUMAN_CONCIERGE',
    primaryProviderId: 'ahmedabad_verified',
    fallbackProviderId: 'ahmedabad_verified',
    supportsSearch: true,
    supportsAvailability: true,
    supportsPricingQuote: true,
    supportsDirectExecution: true,
    supportsModification: true,
    supportsCancellation: true,
    supportsConfirmationValidation: true,
    completionCriterion: 'OPERATOR_VERIFIED_CONFIRMATION',
    requiredInputs: ['requestDescription'],
    optionalInputs: ['urgency', 'budget', 'specialInstructions'],
    hardConstraints: ['requestDescription'],
    recommendationStrategy: 'Senior Concierge assessment and bespoke partner outreach',
    exactly5OptionsStrategy: '5 tailored execution pathways or bespoke proposals curated by senior concierge',
    executionMethod: 'HUMAN_OPERATOR',
    requiresPaymentAuthorization: false,
    requiresBookingReference: false,
    confirmationRequirement: 'Senior Concierge duty log verification and member fulfillment acknowledgment',
    modificationStrategy: 'ASSISTED_OPERATOR',
    cancellationStrategy: 'ASSISTED_OPERATOR',
    escalationTriggers: ['Always routed to Senior Concierge Desk by contract definition'],
  },
};

export function getCategoryContract(category: string): CategoryCapabilityContract {
  const norm = (category || 'other_concierge').toLowerCase().trim().replace(/[\s-]/g, '_');
  if (CATEGORY_AUTOMATION_CONTRACTS[norm]) {
    return CATEGORY_AUTOMATION_CONTRACTS[norm];
  }
  for (const contract of Object.values(CATEGORY_AUTOMATION_CONTRACTS)) {
    if (contract.aliases.includes(norm)) {
      return contract;
    }
  }
  return CATEGORY_AUTOMATION_CONTRACTS['other_concierge'];
}

export function getAllCategoryContracts(): CategoryCapabilityContract[] {
  return Object.values(CATEGORY_AUTOMATION_CONTRACTS);
}
