import type { ProviderAdapterInterface, OptionProposal, ExecutionOutput, VerificationResult } from '../types';

export function isMockModeEnabled(): boolean {
  // Defaults to true in non-production, false in production unless explicitly set
  if (process.env.MOCK_MODE !== undefined) {
    return process.env.MOCK_MODE === 'true';
  }
  return process.env.NODE_ENV !== 'production';
}

export class MockDiningAdapter implements ProviderAdapterInterface {
  readonly providerId = 'mock_dining';
  name = 'OpenTable / Resy Mock Dining Provider';
  supportedCategories = ['dining'];
  readonly environment = 'SANDBOX' as const;

  async search(query: {
    category: string;
    intent?: string;
    rawInput: string;
    constraints?: Record<string, any>;
  }): Promise<OptionProposal[]> {
    const raw = (query.rawInput || '').toLowerCase();
    const city = (query.constraints?.location || query.constraints?.destination || (raw.includes('delhi') ? 'Delhi' : raw.includes('mumbai') ? 'Mumbai' : 'Ahmedabad')).toUpperCase();

    if (city.includes('DELHI')) {
      return [
        {
          id: 'dine-delhi-bukhara',
          providerId: this.providerId,
          providerName: 'Bukhara — ITC Maurya',
          title: 'Legendary Tandoori Dining — Bukhara, ITC Maurya, New Delhi',
          description: 'Iconic world-famous clay-oven culinary heritage. Dal Bukhara, Sikandari Raan, chef signature table.',
          priceAmount: 8500,
          priceCurrency: 'INR',
          priceFormatted: '₹8,500 for two',
          availability: 'Prime 8:30 PM Table Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'North Western Frontier', rating: 4.9 },
        },
        {
          id: 'dine-delhi-indian-accent',
          providerId: this.providerId,
          providerName: 'Indian Accent — The Lodhi',
          title: 'Modern Progressive Indian Tasting Menu — Indian Accent, The Lodhi, New Delhi',
          description: 'Inventive Indian cuisine by Chef Manish Mehrotra. 6-course chef degustation menu with wine pairing option.',
          priceAmount: 11000,
          priceCurrency: 'INR',
          priceFormatted: '₹11,000 for two',
          availability: 'Intimate Corner Booth Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Cancellation up to 6 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Modern Indian', rating: 4.9, private: true },
        },
        {
          id: 'dine-delhi-le-cirque',
          providerId: this.providerId,
          providerName: 'Le Cirque — The Leela Palace',
          title: 'Fine French-Italian Dining — Le Cirque, The Leela Palace, Chanakyapuri',
          description: 'Prestigious French-Italian culinary landmark with private dining room overlooking Chanakyapuri skyline.',
          priceAmount: 12500,
          priceCurrency: 'INR',
          priceFormatted: '₹12,500 for two',
          availability: 'Private Alcove Table Confirmed',
          bookingMethod: 'API',
          cancellationPolicy: 'Full refund 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'French-Italian', rating: 4.8, private: true },
        },
        {
          id: 'dine-delhi-dum-pukht',
          providerId: this.providerId,
          providerName: 'Dum Pukht — ITC Maurya',
          title: 'Royal Awadhi Slow-Cooked Feast — Dum Pukht, ITC Maurya, New Delhi',
          description: 'Centuries-old slow steam dum culinary tradition of the Nawabs of Awadh. Crystal chandeliers and silk service.',
          priceAmount: 9000,
          priceCurrency: 'INR',
          priceFormatted: '₹9,000 for two',
          availability: 'Immediate Reservation Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Awadhi', rating: 4.8 },
        },
        {
          id: 'dine-delhi-orient-express',
          providerId: this.providerId,
          providerName: 'Orient Express — Taj Palace',
          title: 'Belle Époque Carriage Dining — Orient Express, Taj Palace, New Delhi',
          description: 'Recreated legendary luxury train carriage serving European fine dining and vintage champagne.',
          priceAmount: 14000,
          priceCurrency: 'INR',
          priceFormatted: '₹14,000 for two',
          availability: 'Compartment Seating Held',
          bookingMethod: 'API',
          cancellationPolicy: 'Full refund 12 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'European', rating: 4.9, private: true },
        },
        {
          id: 'dine-delhi-megu',
          providerId: this.providerId,
          providerName: 'MEGU — The Leela Palace',
          title: 'Modern Japanese Fine Dining & Robata — MEGU, The Leela Palace, New Delhi',
          description: 'Contemporary Japanese sushi, sashimi, and Sumibi robata grill with 600kg crystal Buddha.',
          priceAmount: 13000,
          priceCurrency: 'INR',
          priceFormatted: '₹13,000 for two',
          availability: 'Sushi Counter / Private Dining Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Japanese', rating: 4.8, private: true },
        },
        {
          id: 'dine-delhi-spice-route',
          providerId: this.providerId,
          providerName: 'The Spice Route — The Imperial',
          title: 'South East Asian Temple Architecture Dining — The Spice Route, The Imperial',
          description: 'Herald of temple art murals and South East Asian spice journey from Malabar to Vietnam.',
          priceAmount: 8000,
          priceCurrency: 'INR',
          priceFormatted: '₹8,000 for two',
          availability: 'Available for Prime Evening Service',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Asian', rating: 4.8 },
        },
        {
          id: 'dine-delhi-varq',
          providerId: this.providerId,
          providerName: 'Varq — The Taj Mahal Hotel',
          title: 'Artisanal Modern Indian Fare — Varq, Taj Mansingh, New Delhi',
          description: 'Precious gold leaf edible art and contemporary reinterpretation of royal Indian recipes.',
          priceAmount: 9500,
          priceCurrency: 'INR',
          priceFormatted: '₹9,500 for two',
          availability: 'Reserved Table Held',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Indian', rating: 4.7 },
        },
        {
          id: 'dine-delhi-kheer',
          providerId: this.providerId,
          providerName: 'Kheer — Roseate House',
          title: 'Contemporary Indian & Live Chaat Bar — Kheer, Roseate House, Aerocity',
          description: 'Chic Japanese architect Noriyoshi Muramatsu designed sanctuary with robata, tandoori, and live dessert atelier.',
          priceAmount: 7500,
          priceCurrency: 'INR',
          priceFormatted: '₹7,500 for two',
          availability: 'Prime 8:00 PM Table',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 2 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Indian', rating: 4.8 },
        },
        {
          id: 'dine-delhi-san-gimignano',
          providerId: this.providerId,
          providerName: 'San Gimignano — The Imperial',
          title: 'Tuscan Courtyard Italian Dining — San Gimignano, The Imperial, New Delhi',
          description: 'Romantic glass pavilion courtyard with white truffles, homemade pasta, and Tuscan reserve cellar.',
          priceAmount: 9200,
          priceCurrency: 'INR',
          priceFormatted: '₹9,200 for two',
          availability: 'Gazebo Seating Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 4 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Delhi', location: 'Delhi', cuisine: 'Italian', rating: 4.8, private: true },
        },
      ];
    }

    // Default Ahmedabad / general fine dining
    return [
      {
        id: 'mock-dine-agashiye',
        providerId: this.providerId,
        providerName: 'Agashiye - The House of MG',
        title: 'Heritage Rooftop Dining - Table for 2',
        description: 'Authentic Gujarati Thali dining on the heritage rooftop terrace. Prime 8:00 PM seating.',
        priceAmount: 3900,
        priceCurrency: 'INR',
        priceFormatted: '₹3,900',
        availability: 'Instant Confirmation Available (Sandbox)',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation up to 4 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
      },
      {
        id: 'mock-dine-royal-vega',
        providerId: this.providerId,
        providerName: 'The Royal Vega - ITC Narmada',
        title: 'Luxury Vegetarian Fine Dining [Sandbox]',
        description: 'Regal dining experience celebrating ancestral Indian cuisine.',
        priceAmount: 5500,
        priceCurrency: 'INR',
        priceFormatted: '₹5,500',
        availability: 'Immediate Reservation Available (Sandbox)',
        bookingMethod: 'API',
        cancellationPolicy: 'Cancellation up to 2 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
      },
      {
        id: 'mock-dine-tinello',
        providerId: this.providerId,
        providerName: 'Tinello — Hyatt Regency',
        title: 'Artisanal Italian Dinner Overlooking Riverfront',
        description: 'Open live kitchen serving handcrafted pasta and wood-fired artisanal pizzas.',
        priceAmount: 4200,
        priceCurrency: 'INR',
        priceFormatted: '₹4,200',
        availability: 'Riverview Table Confirmed',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation up to 2 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
      },
      {
        id: 'mock-dine-nonya',
        providerId: this.providerId,
        providerName: 'Nonya — Taj Skyline',
        title: 'Pan-Asian Gourmet Table',
        description: 'Sichuan, Cantonese, and Southeast Asian delicacies in an opulent contemporary setting.',
        priceAmount: 4800,
        priceCurrency: 'INR',
        priceFormatted: '₹4,800',
        availability: 'Reserved Table Held',
        bookingMethod: 'API',
        cancellationPolicy: 'Cancellation complimentary up to 2 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
      },
      {
        id: 'mock-dine-kuro',
        providerId: this.providerId,
        providerName: 'Kuro — The Renaissance',
        title: 'Modern Asian & Robata Grill Tasting',
        description: 'Sophisticated Pan-Asian grill with craft sushi, dim sum, and bespoke chef pairings.',
        priceAmount: 5200,
        priceCurrency: 'INR',
        priceFormatted: '₹5,200',
        availability: 'Available Prime Seating',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation up to 4 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
      },
    ];
  }

  async execute(proposal: OptionProposal, details: Record<string, any>): Promise<ExecutionOutput> {
    if (!isMockModeEnabled()) {
      return {
        success: false,
        providerId: this.providerId,
        providerName: proposal.providerName,
        status: 'FAILED',
        environment: 'SANDBOX',
        errorMessage: 'Mock automated execution is disabled in live production mode. Escalating to Proventa Concierge Desk.',
        confirmedDetails: {},
      };
    }

    const ref = `[SANDBOX]-DIN-${Math.random().toString(36).substring(2, 9).toUpperCase()}`;
    return {
      success: true,
      providerId: this.providerId,
      externalReferenceId: ref,
      providerName: proposal.providerName,
      status: 'CONFIRMED',
      environment: 'SANDBOX',
      isMock: true,
      rawResponse: {
        provider: 'OpenTable Partner Sandbox',
        status: 'CONFIRMED',
        code: 200,
        pnr: ref,
        timestamp: new Date().toISOString(),
      },
      confirmedDetails: {
        table: 'Priority Seating',
        reference: ref,
        partySize: details.guests || 2,
        notes: details.specialRequests || 'Quiet corner, Proventa VIP guest',
      },
    };
  }

  async verify(referenceId: string): Promise<VerificationResult> {
    return {
      verified: true,
      status: 'CONFIRMED',
      confirmationReference: referenceId,
      environment: 'SANDBOX',
      isMock: true,
      verifiedAt: new Date(),
      auditTrail: `Mock Dining Verification for ${referenceId}`,
    };
  }
}

export class MockHotelAdapter implements ProviderAdapterInterface {
  readonly providerId = 'mock_hotels';
  name = 'Amadeus / Sabre Mock Hotel Provider';
  supportedCategories = ['hotel', 'hotels', 'travel', 'weekend_escapes'];
  readonly environment = 'SANDBOX' as const;

  async search(query: {
    category: string;
    intent?: string;
    rawInput: string;
    constraints?: Record<string, any>;
    location?: string;
    destination?: string;
  }): Promise<OptionProposal[]> {
    const anyQuery = query as any;
    const raw = (anyQuery.rawInput || '').toLowerCase();
    let targetCity = anyQuery.constraints?.destination || anyQuery.constraints?.location || anyQuery.destination || anyQuery.location;
    if (!targetCity) {
      if (raw.includes('delhi')) targetCity = 'Delhi';
      else if (raw.includes('mumbai') || raw.includes('bombay')) targetCity = 'Mumbai';
      else if (raw.includes('bengaluru') || raw.includes('bangalore')) targetCity = 'Bengaluru';
      else if (raw.includes('goa')) targetCity = 'Goa';
      else if (raw.includes('udaipur')) targetCity = 'Udaipur';
      else if (raw.includes('jaipur')) targetCity = 'Jaipur';
      else if (raw.includes('hyderabad')) targetCity = 'Hyderabad';
      else if (raw.includes('kolkata')) targetCity = 'Kolkata';
      else targetCity = 'Ahmedabad';
    }

    const cityUpper = (targetCity || 'AHMEDABAD').toUpperCase();

    if (cityUpper.includes('DELHI')) {
      return [
        {
          id: 'htl-delhi-imperial',
          providerId: this.providerId,
          providerName: 'The Imperial, New Delhi',
          title: 'Heritage Deco Suite — The Imperial, New Delhi',
          description: 'Historic luxury 5-star property on Janpath, Connaught Place. Italian marble bath, butler service, breakfast included.',
          priceAmount: 26000,
          priceCurrency: 'INR',
          priceFormatted: '₹26,000 / night',
          availability: 'Guaranteed Room Availability via GDS Partner Desk',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 24 hours prior to check-in.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Janpath, Connaught Place, New Delhi 110001', checkIn: '14:00', checkOut: '12:00', luxuryScore: 98 },
        } as any,
        {
          id: 'htl-delhi-leela',
          providerId: this.providerId,
          providerName: 'The Leela Palace New Delhi',
          title: 'Grand Deluxe Room — The Leela Palace, Chanakyapuri, New Delhi',
          description: 'Palatial luxury in Diplomatic Enclave with rooftop infinity pool, 24-hr personal butler, airport transfer privileges.',
          priceAmount: 32000,
          priceCurrency: 'INR',
          priceFormatted: '₹32,000 / night',
          availability: '3 Rooms Remaining',
          bookingMethod: 'API',
          cancellationPolicy: 'Refundable up to 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Diplomatic Enclave, Chanakyapuri, New Delhi 110023', checkIn: '14:00', checkOut: '12:00', luxuryScore: 99 },
        } as any,
        {
          id: 'htl-delhi-mansingh',
          providerId: this.providerId,
          providerName: 'The Taj Mahal Hotel (Taj Mansingh)',
          title: 'Taj Club Executive Room — Taj Mansingh, New Delhi',
          description: 'Distinguished Lutyens Delhi address near India Gate. Taj Club lounge access, evening cocktails, airport transfers.',
          priceAmount: 28000,
          priceCurrency: 'INR',
          priceFormatted: '₹28,000 / night',
          availability: 'Confirmed Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: '1 Mansingh Road, New Delhi 110011', checkIn: '14:00', checkOut: '12:00', luxuryScore: 97 },
        } as any,
        {
          id: 'htl-delhi-maurya',
          providerId: this.providerId,
          providerName: 'ITC Maurya, a Luxury Collection Hotel',
          title: 'Chanakya Suite — ITC Maurya, Diplomatic Enclave, New Delhi',
          description: 'Host to world leaders with dedicated Kaya Kalp spa, Bukhara culinary privileges, private butler service.',
          priceAmount: 22000,
          priceCurrency: 'INR',
          priceFormatted: '₹22,000 / night',
          availability: 'Guaranteed Room Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Full refund up to 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Diplomatic Enclave, Sardar Patel Marg, New Delhi 110021', checkIn: '14:00', checkOut: '12:00', luxuryScore: 96 },
        } as any,
        {
          id: 'htl-delhi-lodhi',
          providerId: this.providerId,
          providerName: 'The Lodhi, New Delhi',
          title: 'Lodhi Premier Suite with Private Plunge Pool — The Lodhi',
          description: 'Secluded urban oasis on Lodhi Road. 1,950 sq ft suite featuring a private balcony plunge pool, ultra-discreet private service.',
          priceAmount: 38000,
          priceCurrency: 'INR',
          priceFormatted: '₹38,000 / night',
          availability: '2 Suites Held for Proventa',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Lodhi Road, New Delhi 110003', checkIn: '14:00', checkOut: '12:00', private: true, secluded: true, luxuryScore: 99 },
        } as any,
        {
          id: 'htl-delhi-oberoi',
          providerId: this.providerId,
          providerName: 'The Oberoi, New Delhi',
          title: 'Premier Golf View Room — The Oberoi, New Delhi',
          description: 'Clean air technology sanctuary overlooking Delhi Golf Club and Humayuns Tomb. State of the art automated rooms and butler service.',
          priceAmount: 34000,
          priceCurrency: 'INR',
          priceFormatted: '₹34,000 / night',
          availability: 'Direct Partner Confirmation Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Dr. Zakir Hussain Marg, New Delhi 110003', checkIn: '14:00', checkOut: '12:00', luxuryScore: 99 },
        } as any,
        {
          id: 'htl-delhi-claridges',
          providerId: this.providerId,
          providerName: 'The Claridges, New Delhi',
          title: 'Heritage Suite — The Claridges, Lutyens Delhi',
          description: 'Colonial classic heritage estate on Dr APJ Abdul Kalam Road. Intimate manicured lawns, Dhaba dining privileges.',
          priceAmount: 19500,
          priceCurrency: 'INR',
          priceFormatted: '₹19,500 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: '12 Dr APJ Abdul Kalam Road, New Delhi 110011', checkIn: '14:00', checkOut: '12:00', luxuryScore: 94 },
        } as any,
        {
          id: 'htl-delhi-roseate-resort',
          providerId: this.providerId,
          providerName: 'The Roseate New Delhi',
          title: 'Roseate Private Pool Villa Estate — The Roseate, NH8',
          description: '8-acre secluded architectural sanctuary with serene water bodies, private pool villas, and ultra-private bespoke concierge service.',
          priceAmount: 31000,
          priceCurrency: 'INR',
          priceFormatted: '₹31,000 / night',
          availability: 'Private Villa Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Refundable up to 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'National Highway 8, Samalkha, New Delhi 110037', checkIn: '14:00', checkOut: '12:00', private: true, secluded: true, luxuryScore: 98 },
        } as any,
        {
          id: 'htl-delhi-manor',
          providerId: this.providerId,
          providerName: 'The Manor New Delhi',
          title: 'Discreet Boutique Suite — The Manor, Friends Colony',
          description: 'Exclusive 14-key private boutique hotel in leafy residential Friends Colony. Private garden terrace, bespoke butler.',
          priceAmount: 21000,
          priceCurrency: 'INR',
          priceFormatted: '₹21,000 / night',
          availability: 'Available for Immediate Booking',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: '77 Friends Colony West, New Delhi 110065', checkIn: '14:00', checkOut: '12:00', private: true, boutique: true, luxuryScore: 95 },
        } as any,
        {
          id: 'htl-delhi-andaz',
          providerId: this.providerId,
          providerName: 'Andaz Delhi by Hyatt',
          title: 'Runway View Luxury Suite — Andaz Delhi, Aerocity',
          description: 'Art-inspired luxury suites celebrating Delhi. Curated minibar, artisanal dining at AnnaMaya, soundproof runway views.',
          priceAmount: 18000,
          priceCurrency: 'INR',
          priceFormatted: '₹18,000 / night',
          availability: 'Guaranteed Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Asset No. 1, Aerocity, New Delhi 110037', checkIn: '14:00', checkOut: '12:00', luxuryScore: 93 },
        } as any,
        {
          id: 'htl-delhi-jw-aerocity',
          providerId: this.providerId,
          providerName: 'JW Marriott Hotel New Delhi Aerocity',
          title: 'Executive Club Room — JW Marriott Aerocity',
          description: 'Spacious upscale rooms with marble bath, Quan Spa access, club lounge privileges, 5 minutes from Terminal 3.',
          priceAmount: 19000,
          priceCurrency: 'INR',
          priceFormatted: '₹19,000 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Asset Area 4, Hospitality District, Aerocity, New Delhi 110037', checkIn: '14:00', checkOut: '12:00', luxuryScore: 94 },
        } as any,
        {
          id: 'htl-delhi-tajpalace',
          providerId: this.providerId,
          providerName: 'Taj Palace, New Delhi',
          title: 'Luxury Park View Room — Taj Palace, Dhaula Kuan',
          description: 'Set amidst 6 acres of lush greenery with Orient Express fine dining, heated swimming pool, luxury Taj amenities.',
          priceAmount: 23000,
          priceCurrency: 'INR',
          priceFormatted: '₹23,000 / night',
          availability: 'Room Confirmed',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: '2 Sardar Patel Marg, Diplomatic Enclave, New Delhi 110021', checkIn: '14:00', checkOut: '12:00', luxuryScore: 96 },
        } as any,
        {
          id: 'htl-delhi-shangrila',
          providerId: this.providerId,
          providerName: 'Shangri-La Eros New Delhi',
          title: 'Horizon Club Deluxe Room — Shangri-La Eros',
          description: 'Panoramic views of historic Delhi from Connaught Place. Horizon Club privileges, private lounge, Shang Palace dining.',
          priceAmount: 21500,
          priceCurrency: 'INR',
          priceFormatted: '₹21,500 / night',
          availability: '3 Rooms Remaining',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: '19 Ashoka Road, Connaught Place, New Delhi 110001', checkIn: '14:00', checkOut: '12:00', luxuryScore: 95 },
        } as any,
        {
          id: 'htl-delhi-private-estate',
          providerId: this.providerId,
          providerName: 'Proventa Private Villa Reserve — Chhatarpur',
          title: 'Exclusive 4-Bedroom Private Country Estate — Chhatarpur / Mehrauli',
          description: 'Gated private farmhouse estate with heated lap pool, personal chef, dedicated butler team, ultra-private sanctuary.',
          priceAmount: 48000,
          priceCurrency: 'INR',
          priceFormatted: '₹48,000 / night',
          availability: 'Exclusive Key Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Non-refundable deposit, reschedule permitted.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'DLF Farms, Chhatarpur, New Delhi 110074', checkIn: '15:00', checkOut: '11:00', private: true, secluded: true, luxuryScore: 99 },
        } as any,
        {
          id: 'htl-delhi-roseate-house',
          providerId: this.providerId,
          providerName: 'Roseate House New Delhi',
          title: 'Junior Suite — Roseate House, Aerocity',
          description: 'Cosmopolitan luxury suite with automated mood lighting, deep soaking tub, private movie theatre cinema screening access.',
          priceAmount: 18500,
          priceCurrency: 'INR',
          priceFormatted: '₹18,500 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Delhi',
          metadata: { city: 'Delhi', arrivalCity: 'Delhi', address: 'Asset 10, Northern Access Road, Aerocity, New Delhi 110037', checkIn: '14:00', checkOut: '12:00', boutique: true, luxuryScore: 94 },
        } as any,
      ];
    }

    if (cityUpper.includes('MUMBAI')) {
      return [
        {
          id: 'htl-mumbai-tajpalace',
          providerId: this.providerId,
          providerName: 'The Taj Mahal Palace, Mumbai',
          title: 'Sea View Luxury Room — The Taj Mahal Palace, Colaba, Mumbai',
          description: 'Iconic heritage landmark facing the Gateway of India. Sea-facing view, Palace lounge access, butler service.',
          priceAmount: 35000,
          priceCurrency: 'INR',
          priceFormatted: '₹35,000 / night',
          availability: 'Guaranteed Heritage Wing Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Full refund 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: 'Apollo Bunder, Colaba, Mumbai 400001', checkIn: '14:00', checkOut: '12:00', luxuryScore: 99 },
        } as any,
        {
          id: 'htl-mumbai-oberoi',
          providerId: this.providerId,
          providerName: 'The Oberoi, Mumbai',
          title: 'Premier Ocean View — The Oberoi, Marine Drive, Nariman Point, Mumbai',
          description: 'Panoramic views of the Arabian Sea and Marine Drive. Floor-to-ceiling glass, 24-hr butler, luxury bath.',
          priceAmount: 28000,
          priceCurrency: 'INR',
          priceFormatted: '₹28,000 / night',
          availability: '2 Rooms Remaining',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: 'Nariman Point, Marine Drive, Mumbai 400021', checkIn: '14:00', checkOut: '12:00', luxuryScore: 98 },
        } as any,
        {
          id: 'htl-mumbai-stregis',
          providerId: this.providerId,
          providerName: 'The St. Regis Mumbai',
          title: 'Grand Deluxe Skyline Room — The St. Regis Mumbai, Lower Parel',
          description: 'India tallest luxury hotel with signature St. Regis Butler Service, infinity pool, luxury Palladium Mall access.',
          priceAmount: 24000,
          priceCurrency: 'INR',
          priceFormatted: '₹24,000 / night',
          availability: 'Skyline View Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: '462 Senapati Bapat Marg, Lower Parel, Mumbai 400013', checkIn: '15:00', checkOut: '12:00', luxuryScore: 96 },
        } as any,
        {
          id: 'htl-mumbai-tajlandsend',
          providerId: this.providerId,
          providerName: 'Taj Lands End, Mumbai',
          title: 'Sea View Executive Room — Taj Lands End, Bandra West, Mumbai',
          description: 'Overlooking the Arabian Sea and Bandra-Worli Sea Link. Executive lounge privileges, poolside cabanas.',
          priceAmount: 22500,
          priceCurrency: 'INR',
          priceFormatted: '₹22,500 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: 'BJ Road, Bandstand, Bandra West, Mumbai 400050', checkIn: '14:00', checkOut: '12:00', luxuryScore: 95 },
        } as any,
        {
          id: 'htl-mumbai-fourseasons',
          providerId: this.providerId,
          providerName: 'Four Seasons Hotel Mumbai',
          title: 'Premier Sea View Suite — Four Seasons Hotel Mumbai, Worli',
          description: 'Sophisticated contemporary sanctuary in Worli. Aer rooftop bar privileges, expansive marble bath, private spa.',
          priceAmount: 26000,
          priceCurrency: 'INR',
          priceFormatted: '₹26,000 / night',
          availability: 'Available for Immediate Booking',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: '1/136 Dr E Moses Rd, Worli, Mumbai 400018', checkIn: '15:00', checkOut: '12:00', luxuryScore: 96 },
        } as any,
        {
          id: 'htl-mumbai-jwm-juhu',
          providerId: this.providerId,
          providerName: 'JW Marriott Mumbai Juhu',
          title: 'Oceanfront Luxury Suite — JW Marriott Juhu, Mumbai',
          description: 'Beachfront resort directly on Juhu Beach with salt-water pools, Quan Spa, celebrity dining hotspots.',
          priceAmount: 27000,
          priceCurrency: 'INR',
          priceFormatted: '₹27,000 / night',
          availability: 'Oceanfront View Guaranteed',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: 'Juhu Tara Road, Juhu, Mumbai 400049', checkIn: '15:00', checkOut: '12:00', luxuryScore: 95 },
        } as any,
        {
          id: 'htl-mumbai-sohohouse',
          providerId: this.providerId,
          providerName: 'Soho House Mumbai',
          title: 'Private Member Club Bedroom — Soho House, Juhu Beach',
          description: 'Bespoke 38-room private club retreat facing the Arabian Sea. Vintage Rajasthani textiles, rooftop pool, ultra-private atmosphere.',
          priceAmount: 32000,
          priceCurrency: 'INR',
          priceFormatted: '₹32,000 / night',
          availability: 'Exclusive Member Key Held',
          bookingMethod: 'API',
          cancellationPolicy: 'Refundable up to 72 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: '16 Juhu Tara Road, Mumbai 400049', checkIn: '15:00', checkOut: '12:00', private: true, secluded: true, boutique: true, luxuryScore: 98 },
        } as any,
        {
          id: 'htl-mumbai-trident',
          providerId: this.providerId,
          providerName: 'Trident Nariman Point, Mumbai',
          title: 'Trident Club Ocean View — Trident Nariman Point',
          description: 'Prime Marine Drive location with Arabian sea panoramas. Club lounge breakfast, high tea, evening cocktails.',
          priceAmount: 18000,
          priceCurrency: 'INR',
          priceFormatted: '₹18,000 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: 'Nariman Point, Mumbai 400021', checkIn: '14:00', checkOut: '12:00', luxuryScore: 93 },
        } as any,
        {
          id: 'htl-mumbai-itcgrandcentral',
          providerId: this.providerId,
          providerName: 'ITC Grand Central, a Luxury Collection Hotel',
          title: 'ITC One Suite — ITC Grand Central, Parel, Mumbai',
          description: 'Victorian architecture in historic Parel with dedicated Kaya Kalp spa, luxury lounge, butler service.',
          priceAmount: 19500,
          priceCurrency: 'INR',
          priceFormatted: '₹19,500 / night',
          availability: 'Room Guaranteed',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: '287 Dr Babasaheb Ambedkar Rd, Parel, Mumbai 400012', checkIn: '14:00', checkOut: '12:00', luxuryScore: 94 },
        } as any,
        {
          id: 'htl-mumbai-tajsantacruz',
          providerId: this.providerId,
          providerName: 'Taj Santacruz, Mumbai',
          title: 'Luxury Runway View Suite — Taj Santacruz',
          description: 'Directly overlooking Mumbai airport runway with soundproof floor-to-ceiling glass, 24-hr butler, airport transit VIP privileges.',
          priceAmount: 21000,
          priceCurrency: 'INR',
          priceFormatted: '₹21,000 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          location: 'Mumbai',
          metadata: { city: 'Mumbai', arrivalCity: 'Mumbai', address: 'Domestic Airport, Off Western Express Highway, Santacruz East, Mumbai 400099', checkIn: '14:00', checkOut: '12:00', luxuryScore: 95 },
        } as any,
      ];
    }

    if (cityUpper.includes('BENGALURU') || cityUpper.includes('BANGALORE')) {
      return [
        {
          id: 'htl-blr-leela',
          providerId: this.providerId,
          providerName: 'The Leela Palace Bengaluru',
          title: 'Royal Premier Room — The Leela Palace, Old Airport Road, Bengaluru',
          description: 'Architecture inspired by the Mysore Royal Palace, set in 7 acres of lush gardens. Balcony with waterfall view.',
          priceAmount: 24000,
          priceCurrency: 'INR',
          priceFormatted: '₹24,000 / night',
          availability: 'Confirmed Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Full refund 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Bengaluru', arrivalCity: 'Bengaluru', address: '23 HAL Old Airport Rd, Bengaluru 560008', checkIn: '14:00', checkOut: '12:00' },
        },
        {
          id: 'htl-blr-tajwestend',
          providerId: this.providerId,
          providerName: 'The Taj West End, Bengaluru',
          title: 'Garden Heritage Suite — The Taj West End, Race Course Road',
          description: 'Historic 1887 heritage sanctuary set within 20 acres of tropical flora. Private verandah, dedicated butler.',
          priceAmount: 22000,
          priceCurrency: 'INR',
          priceFormatted: '₹22,000 / night',
          availability: 'Guaranteed Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Bengaluru', arrivalCity: 'Bengaluru', address: 'Race Course Road, Bengaluru 560001', checkIn: '14:00', checkOut: '12:00', private: true },
        },
        {
          id: 'htl-blr-oberoi',
          providerId: this.providerId,
          providerName: 'The Oberoi, Bengaluru',
          title: 'Deluxe Garden View Room — The Oberoi, MG Road, Bengaluru',
          description: 'Tropical oasis centered around a centenarian rain tree on MG Road. Private balcony, personalized butler service.',
          priceAmount: 23500,
          priceCurrency: 'INR',
          priceFormatted: '₹23,500 / night',
          availability: 'Room Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Bengaluru', arrivalCity: 'Bengaluru', address: '37-39 MG Road, Bengaluru 560001', checkIn: '14:00', checkOut: '12:00' },
        },
        {
          id: 'htl-blr-fourseasons',
          providerId: this.providerId,
          providerName: 'Four Seasons Hotel Bengaluru at Embassy ONE',
          title: 'Executive Suite — Four Seasons Hotel Bengaluru',
          description: 'Contemporary design with private gardens and cascading outdoor pool. Far & East Asian rooftop dining privileges.',
          priceAmount: 21000,
          priceCurrency: 'INR',
          priceFormatted: '₹21,000 / night',
          availability: 'Confirmed Allocation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Bengaluru', arrivalCity: 'Bengaluru', address: 'Bellary Rd, Dena Bank Colony, Ganganagar, Bengaluru 560032', checkIn: '15:00', checkOut: '12:00' },
        },
        {
          id: 'htl-blr-itcgardenia',
          providerId: this.providerId,
          providerName: 'ITC Gardenia, a Luxury Collection Hotel',
          title: 'Pelican Suite — ITC Gardenia, Residency Road, Bengaluru',
          description: 'LEED platinum luxury hotel in central Bengaluru with open helipad, Edo Japanese restaurant, Kaya Kalp spa.',
          priceAmount: 20000,
          priceCurrency: 'INR',
          priceFormatted: '₹20,000 / night',
          availability: 'Available Immediate Confirmation',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Bengaluru', arrivalCity: 'Bengaluru', address: '1 Residency Rd, Ashok Nagar, Bengaluru 560025', checkIn: '14:00', checkOut: '12:00' },
        },
      ];
    }

    if (cityUpper.includes('GOA')) {
      return [
        {
          id: 'htl-goa-tajexotica',
          providerId: this.providerId,
          providerName: 'Taj Exotica Resort & Spa, Goa',
          title: 'Mediterranean Sea-Facing Villa — Taj Exotica, Benaulim, Goa',
          description: 'Spread across 56 acres along the pristine Benaulim beach. Private plunge pool, Jiva Spa access, breakfast included.',
          priceAmount: 32000,
          priceCurrency: 'INR',
          priceFormatted: '₹32,000 / night',
          availability: 'Confirmed Villa Availability',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation up to 72 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Goa', arrivalCity: 'Goa', address: 'Calwaddo, Benaulim, Goa 403716', checkIn: '15:00', checkOut: '11:00', private: true },
        },
        {
          id: 'htl-goa-tajfortaguada',
          providerId: this.providerId,
          providerName: 'Taj Fort Aguada Resort & Spa, Goa',
          title: 'Hermitage Villa — Taj Fort Aguada, Candolim, Goa',
          description: 'Historic ramparts of 16th century Portuguese fortress overlooking the Arabian Sea. Luxury sunset terrace.',
          priceAmount: 28000,
          priceCurrency: 'INR',
          priceFormatted: '₹28,000 / night',
          availability: 'Hermitage Villa Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 72 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Goa', arrivalCity: 'Goa', address: 'Sinquerim, Candolim, Goa 403515', checkIn: '15:00', checkOut: '11:00' },
        },
        {
          id: 'htl-goa-w',
          providerId: this.providerId,
          providerName: 'W Goa, Vagator',
          title: 'Marvelous Chalet — W Goa, Vagator Beach',
          description: 'Chic beachside luxury beneath Chapora Fort. Rockpool sunset views, private plunge pool chalet, Clarins spa.',
          priceAmount: 29500,
          priceCurrency: 'INR',
          priceFormatted: '₹29,500 / night',
          availability: 'Chalet Confirmed',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Goa', arrivalCity: 'Goa', address: 'Vagator Beach, Bardez, Goa 403509', checkIn: '15:00', checkOut: '12:00' },
        },
        {
          id: 'htl-goa-stregis',
          providerId: this.providerId,
          providerName: 'The St. Regis Goa Resort',
          title: 'Manor Pool Suite — The St. Regis Goa, Mobor Beach',
          description: '49-acre secluded sanctuary nestled between the Sal River and Arabian Sea. Signature St. Regis butler service, golf course.',
          priceAmount: 34000,
          priceCurrency: 'INR',
          priceFormatted: '₹34,000 / night',
          availability: 'Pool Suite Reserved',
          bookingMethod: 'API',
          cancellationPolicy: 'Refundable up to 72 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Goa', arrivalCity: 'Goa', address: 'Mobor Beach, Cavelossim, Goa 403731', checkIn: '15:00', checkOut: '11:00', private: true, secluded: true },
        },
        {
          id: 'htl-goa-alila',
          providerId: this.providerId,
          providerName: 'Alila Diwa Goa by Hyatt',
          title: 'Diwa Club Suite with Private Lap Pool Access — Alila Diwa, Majorda',
          description: 'Contemporary Goan architecture overlooking lush paddy fields. Private enclave with dedicated lap pool and lounge.',
          priceAmount: 22000,
          priceCurrency: 'INR',
          priceFormatted: '₹22,000 / night',
          availability: 'Guaranteed Available',
          bookingMethod: 'API',
          cancellationPolicy: 'Complimentary cancellation 48 hours prior.',
          environment: 'SANDBOX',
          isMock: true,
          metadata: { city: 'Goa', arrivalCity: 'Goa', address: '48/10 Adao Waddo, Majorda, Goa 403713', checkIn: '15:00', checkOut: '12:00', boutique: true },
        },
      ];
    }

    // Default: Ahmedabad Luxury Inventory
    return [
      {
        id: 'htl-amd-itc-narmada',
        providerId: this.providerId,
        providerName: 'ITC Narmada, a Luxury Collection Hotel',
        title: `Executive Club Suite — ITC Narmada, Bodakdev, Ahmedabad`,
        description: 'King bed suite with skyline views, club lounge access, breakfast included.',
        priceAmount: 24000,
        priceCurrency: 'INR',
        priceFormatted: '₹24,000 / night',
        availability: 'Guaranteed Room Availability',
        bookingMethod: 'API',
        cancellationPolicy: 'Full refund 24 hours prior to check-in.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city: 'Ahmedabad', arrivalCity: 'Ahmedabad', address: 'Bodakdev, Ahmedabad' },
      },
      {
        id: 'htl-amd-taj-skyline',
        providerId: this.providerId,
        providerName: 'Taj Skyline, Ahmedabad',
        title: `Luxury King Room — Taj Skyline, Ahmedabad`,
        description: 'Contemporary luxury room with city view, complimentary airport transfer.',
        priceAmount: 18500,
        priceCurrency: 'INR',
        priceFormatted: '₹18,500 / night',
        availability: '2 rooms remaining',
        bookingMethod: 'API',
        cancellationPolicy: 'Non-refundable rate.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city: 'Ahmedabad', arrivalCity: 'Ahmedabad', address: 'Sindhu Bhavan Road, Ahmedabad' },
      },
      {
        id: 'htl-amd-hyatt-regency',
        providerId: this.providerId,
        providerName: 'Hyatt Regency Ahmedabad',
        title: 'Riverfront Club Suite — Hyatt Regency, Ashram Road',
        description: 'Spectacular views of Sabarmati Riverfront, Regency Club lounge privileges, Italian dining at Tinello.',
        priceAmount: 16500,
        priceCurrency: 'INR',
        priceFormatted: '₹16,500 / night',
        availability: 'Riverview Suite Confirmed',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city: 'Ahmedabad', arrivalCity: 'Ahmedabad', address: 'Ashram Road, Ahmedabad 380014' },
      },
      {
        id: 'htl-amd-house-of-mg',
        providerId: this.providerId,
        providerName: 'The House of MG Heritage Hotel',
        title: 'Grand Heritage Suite — The House of MG, Old Ahmedabad',
        description: 'Restored 1924 ancestral mansion suite with antique rosewood furniture, private verandah, and Agashiye rooftop access.',
        priceAmount: 15000,
        priceCurrency: 'INR',
        priceFormatted: '₹15,000 / night',
        availability: 'Heritage Key Held',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation 48 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city: 'Ahmedabad', arrivalCity: 'Ahmedabad', address: 'Lal Darwaja, Ahmedabad 380001', private: true, heritage: true },
      },
      {
        id: 'htl-amd-renaissance',
        providerId: this.providerId,
        providerName: 'Renaissance Ahmedabad Hotel',
        title: 'Executive Suite — Renaissance Ahmedabad, SG Highway',
        description: 'Rooftop infinity pool, club lounge access, luxury Kuro Asian dining privileges.',
        priceAmount: 14500,
        priceCurrency: 'INR',
        priceFormatted: '₹14,500 / night',
        availability: 'Guaranteed Available',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation 24 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city: 'Ahmedabad', arrivalCity: 'Ahmedabad', address: 'SG Highway, Gota, Ahmedabad 380060' },
      },
    ];
  }

  async execute(proposal: OptionProposal, details: Record<string, any>): Promise<ExecutionOutput> {
    const ref = `[MOCK]-HTL-${Math.random().toString(36).substring(2, 9).toUpperCase()}`;
    return {
      success: true,
      providerId: this.providerId,
      externalReferenceId: ref,
      providerName: proposal.providerName,
      status: 'CONFIRMED',
      environment: 'SANDBOX',
      isMock: true,
      rawResponse: {
        gds: 'Amadeus Mock Sandbox',
        status: 'HK' /* Holds Confirmed */,
        pnr: ref,
        provider: proposal.providerName,
      },
      confirmedDetails: {
        bookingRef: ref,
        nights: details.nights || 1,
        checkIn: details.checkIn || '14:00',
        checkOut: '12:00',
        breakfastIncluded: true,
      },
    };
  }

  async verify(referenceId: string): Promise<VerificationResult> {
    return {
      verified: true,
      status: 'CONFIRMED',
      confirmationReference: referenceId,
      environment: 'SANDBOX',
      isMock: referenceId.includes('MOCK') || true,
      verifiedAt: new Date(),
      auditTrail: `GDS PNR status confirmed via mock GDS verification. Reference: ${referenceId}`,
    };
  }
}

export class MockMobilityAdapter implements ProviderAdapterInterface {
  readonly providerId = 'mock_mobility';
  name = 'Blacklane / Luxury Chauffeur Fleet Adapter';
  supportedCategories = ['mobility', 'transit'];
  readonly environment = 'SANDBOX' as const;

  async search(query: {
    category: string;
    intent?: string;
    rawInput: string;
    constraints?: Record<string, any>;
  }): Promise<OptionProposal[]> {
    return [
      {
        id: `mock-mob-1-${Date.now()}`,
        providerId: this.providerId,
        providerName: 'Proventa Chauffeur Network - SVPIA Fleet',
        title: 'Mercedes-Benz E-Class Executive Airport Transfer',
        description: 'Chauffeur meet & greet at SVPIA arrival terminal, bottled water, Wi-Fi, flight tracking.',
        priceAmount: 1800,
        priceCurrency: 'INR',
        priceFormatted: '₹1,800',
        availability: 'Dedicated Driver Assigned on Approval',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation up to 1 hour prior.',
        environment: 'SANDBOX',
        isMock: true,
      },
    ];
  }

  async execute(proposal: OptionProposal, details: Record<string, any>): Promise<ExecutionOutput> {
    const ref = `[MOCK]-CHAUFF-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
    return {
      success: true,
      providerId: this.providerId,
      externalReferenceId: ref,
      providerName: proposal.providerName,
      status: 'CONFIRMED',
      environment: 'SANDBOX',
      isMock: true,
      rawResponse: {
        fleetStatus: 'DRIVER_DISPATCHED',
        driverName: 'Ramesh Patel',
        vehicle: 'Mercedes-Benz E-Class (GJ-01-XX-9988)',
        tripId: ref,
      },
      confirmedDetails: {
        tripId: ref,
        driver: 'Ramesh Patel',
        car: 'Mercedes-Benz E-Class',
        pickupTime: details.scheduledTime || 'Promptly as requested',
      },
    };
  }

  async verify(referenceId: string): Promise<VerificationResult> {
    return {
      verified: true,
      status: 'CONFIRMED',
      confirmationReference: referenceId,
      environment: 'SANDBOX',
      isMock: referenceId.includes('MOCK') || true,
      verifiedAt: new Date(),
      auditTrail: `Fleet dispatch telemetry confirmed via mobility partner mock API. Reference: ${referenceId}`,
    };
  }
}

export class MockShoppingAdapter implements ProviderAdapterInterface {
  readonly providerId = 'mock_shopping';
  name = 'Luxury Retail & Concierge Gifting Adapter';
  supportedCategories = ['shopping', 'gift', 'gifts'];
  readonly environment = 'SANDBOX' as const;

  async search(query: {
    category: string;
    intent?: string;
    rawInput: string;
    constraints?: Record<string, any>;
  }): Promise<OptionProposal[]> {
    return [
      {
        id: `mock-gft-hamper-1`,
        providerId: this.providerId,
        providerName: 'Forest Essentials & Bateel Confections',
        title: 'Bespoke Royal Amber & Saffron Luxury Hamper',
        description: 'Artisanal organic Ayurvedic body care collection paired with organic medjool dates in a handcrafted brass-inlay box.',
        priceAmount: 8500,
        priceCurrency: 'INR',
        priceFormatted: '₹8,500',
        availability: 'Ready for Express White-Glove Dispatch',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation prior to courier dispatch.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { category: 'gift', boutique: true, delivery: 'Same Day' },
      },
      {
        id: `mock-gft-silver-2`,
        providerId: this.providerId,
        providerName: 'MMTC-PAMP & Frazer and Haws',
        title: 'Hallmarked Pure Silver Lotus Tea-Light & Coin Gift Set',
        description: '999.9 purity fine silver coin and hand-engraved silver lotus votive with embossed Proventa velvet presentation box.',
        priceAmount: 7200,
        priceCurrency: 'INR',
        priceFormatted: '₹7,200',
        availability: 'Available for Immediate Dispatch',
        bookingMethod: 'API',
        cancellationPolicy: 'Refundable prior to courier pickup.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { category: 'gift', boutique: true, delivery: 'Express' },
      },
      {
        id: `mock-gft-silk-3`,
        providerId: this.providerId,
        providerName: 'Bandhej Heritage Textiles',
        title: 'Handcrafted Tussar & Mulberry Silk Stole Gift Box',
        description: 'Authentic Indian handloom silk stole in rich jewel tones with calligraphy note and silk-tied packaging.',
        priceAmount: 6500,
        priceCurrency: 'INR',
        priceFormatted: '₹6,500',
        availability: 'In Stock — Gift Box Ready',
        bookingMethod: 'API',
        cancellationPolicy: 'Refundable before fulfillment.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { category: 'gift', delivery: 'Same Day' },
      },
      {
        id: `mock-gft-scent-4`,
        providerId: this.providerId,
        providerName: 'Bombay Perfumery & Artisanal Fragrances',
        title: 'Rare Botanicals Discovery Curation & Brass Candle Set',
        description: 'Limited-edition Eau de Parfum paired with small-batch hand-poured soy wax candles in polished brass vessels.',
        priceAmount: 4800,
        priceCurrency: 'INR',
        priceFormatted: '₹4,800',
        availability: 'Allocated for Proventa Members',
        bookingMethod: 'API',
        cancellationPolicy: 'Refundable before dispatch.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { category: 'gift', delivery: 'Standard' },
      },
      {
        id: `mock-gft-gourmet-5`,
        providerId: this.providerId,
        providerName: 'Subko Coffee & Paul and Mike Cacao',
        title: 'Reserve Estate Single-Origin Coffee & Rare Chocolate Chest',
        description: 'Selection of three single-estate micro-lot coffees and artisanal farmer-direct dark chocolate tablets.',
        priceAmount: 3800,
        priceCurrency: 'INR',
        priceFormatted: '₹3,800',
        availability: 'Immediate Dispatch Available',
        bookingMethod: 'API',
        cancellationPolicy: 'Complimentary cancellation 2 hours prior.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { category: 'gift', delivery: 'Express' },
      },
    ];
  }

  async execute(proposal: OptionProposal, details: Record<string, any>): Promise<ExecutionOutput> {
    const ref = `[MOCK]-GIFT-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
    return {
      success: true,
      providerId: this.providerId,
      externalReferenceId: ref,
      providerName: proposal.providerName,
      status: 'CONFIRMED',
      environment: 'SANDBOX',
      isMock: true,
      rawResponse: {
        boutiqueOrderRef: ref,
        status: 'ORDER_PLACED_PACKAGING',
      },
      confirmedDetails: {
        orderId: ref,
        giftNote: details.giftNote || 'With warm compliments',
        deliveryAddress: details.deliveryAddress || 'Client Residence',
      },
    };
  }

  async verify(referenceId: string): Promise<VerificationResult> {
    return {
      verified: true,
      status: 'CONFIRMED',
      confirmationReference: referenceId,
      environment: 'SANDBOX',
      isMock: referenceId.includes('MOCK') || true,
      verifiedAt: new Date(),
      auditTrail: `Boutique order verified via retail partner mock inventory system. Reference: ${referenceId}`,
    };
  }
}

export class MockResearchPlanningAdapter implements ProviderAdapterInterface {
  readonly providerId = 'mock_research_planning';
  name = 'Proventa Research & Intelligence Desk';
  supportedCategories = ['research', 'planning', 'research_planning', 'personal'];
  readonly environment = 'SANDBOX' as const;

  async search(query: {
    category: string;
    intent?: string;
    rawInput: string;
    constraints?: Record<string, any>;
  }): Promise<OptionProposal[]> {
    const raw = (query.rawInput || '').toLowerCase();
    const city = raw.includes('delhi') ? 'Delhi' : raw.includes('mumbai') ? 'Mumbai' : 'Ahmedabad';

    return [
      {
        id: 'plan-delhi-curated-3day-1',
        providerId: this.providerId,
        providerName: 'Proventa Curatorial Desk',
        title: `Curated Three-Day Private Cultural & Heritage Dossier — ${city}`,
        description: `Comprehensive 72-hour executive itinerary featuring VIP monument entries, private heritage walks, curated dining, and chauffeur scheduling in ${city}.`,
        priceAmount: 0,
        priceCurrency: 'INR',
        priceFormatted: 'Complimentary Member Curation',
        availability: 'Instant Digital Dossier Ready',
        bookingMethod: 'API',
        cancellationPolicy: 'Flexible consultation itinerary.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city, isDeliverable: true, duration: '3 Days', private: true },
      },
      {
        id: 'plan-delhi-lutyens-architecture-2',
        providerId: this.providerId,
        providerName: 'Lutyens Heritage Advisory',
        title: `Imperial Architectural & Historic Walking Guide — ${city}`,
        description: `Private architectural exploration of historic estates, colonial landmarks, and diplomatic avenues with reservations at iconic tea rooms.`,
        priceAmount: 0,
        priceCurrency: 'INR',
        priceFormatted: 'Complimentary Member Curation',
        availability: 'Customized Dossier Generated',
        bookingMethod: 'API',
        cancellationPolicy: 'Flexible itinerary.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city, isDeliverable: true, private: true },
      },
      {
        id: 'plan-delhi-private-art-museums-3',
        providerId: this.providerId,
        providerName: 'Contemporary Art & Culture Bureau',
        title: `Private Gallery & Collector Studio Access Circuit — ${city}`,
        description: `Curated gallery trail covering Kiran Nadar Museum of Art, private foundation studios, and behind-the-scenes previews.`,
        priceAmount: 0,
        priceCurrency: 'INR',
        priceFormatted: 'Complimentary Member Curation',
        availability: 'Available Immediately',
        bookingMethod: 'API',
        cancellationPolicy: 'Flexible itinerary.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city, isDeliverable: true },
      },
      {
        id: 'plan-delhi-culinary-spice-trail-4',
        providerId: this.providerId,
        providerName: 'Culinary Intelligence Guild',
        title: `Royal Spice Trail & Progressive Gastronomy Guide — ${city}`,
        description: `Chronological tasting trail from centuries-old Old City haveli kitchens to progressive Michelin-caliber tasting menus.`,
        priceAmount: 0,
        priceCurrency: 'INR',
        priceFormatted: 'Complimentary Member Curation',
        availability: 'Immediate Download',
        bookingMethod: 'API',
        cancellationPolicy: 'Flexible itinerary.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city, isDeliverable: true },
      },
      {
        id: 'plan-delhi-wellness-retreat-golf-5',
        providerId: this.providerId,
        providerName: 'NCR Sporting & Wellness Guild',
        title: `Exclusive Golf Course & Private Spa Day Itinerary — ${city}`,
        description: `Championship course tee times, Kaya Kalp / Lodhi spa hydrotherapy sessions, and secluded dining arrangements.`,
        priceAmount: 0,
        priceCurrency: 'INR',
        priceFormatted: 'Complimentary Member Curation',
        availability: 'Instant Dossier Ready',
        bookingMethod: 'API',
        cancellationPolicy: 'Flexible itinerary.',
        environment: 'SANDBOX',
        isMock: true,
        metadata: { city, isDeliverable: true },
      },
    ];
  }

  async execute(proposal: OptionProposal, details: Record<string, any>): Promise<ExecutionOutput> {
    return {
      success: true,
      providerId: this.providerId,
      providerName: proposal.providerName,
      status: 'CONFIRMED',
      environment: 'SANDBOX',
      isMock: true,
      confirmedDetails: {
        deliverableType: 'CURATED_DOSSIER',
        title: proposal.title,
        content: proposal.description,
      },
    };
  }

  async verify(referenceId: string): Promise<VerificationResult> {
    return {
      verified: true,
      status: 'CONFIRMED',
      environment: 'SANDBOX',
      isMock: true,
      verifiedAt: new Date(),
      auditTrail: 'Dossier curation verified by Curatorial Intelligence Desk.',
    };
  }
}
